<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManagePayees.aspx.cs" Inherits="Jason_Kidrowski_Final_Project_2._0.ManagePayees" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Menu ID="MainMenu" runat="server" BackColor="#F7F6F3" DynamicHorizontalOffset="2" Font-Names="Verdana" Font-Size="0.8em" ForeColor="#7C6F57" Orientation="Horizontal" StaticSubMenuIndent="10px" Visible="True">
                <DynamicHoverStyle BackColor="#7C6F57" ForeColor="White" />
                <DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
                <DynamicMenuStyle BackColor="#F7F6F3" />
                <DynamicSelectedStyle BackColor="#5D7B9D" />
                <Items>
                    <asp:MenuItem NavigateUrl="~/Login.aspx" Text="Home" Value="Home"></asp:MenuItem>
                    <asp:MenuItem NavigateUrl="~/PayABill.aspx" Text="Pay Bill" Value="Pay Bill"></asp:MenuItem>
                    <asp:MenuItem NavigateUrl="~/ManagePayees.aspx" Text="Manage Payees" Value="Manage Payees"></asp:MenuItem>
                    <asp:MenuItem NavigateUrl="~/PaymentHistory.aspx" Text="Payment History" Value="Payment History"></asp:MenuItem>
                    <asp:MenuItem NavigateUrl="~/AccountSettings.aspx" Text="Account Settings" Value="Account Settings"></asp:MenuItem>
                    <asp:MenuItem Text="Logout" Value="Logout" NavigateUrl="~/Logout.aspx"></asp:MenuItem>
                </Items>
                <StaticHoverStyle BackColor="#7C6F57" ForeColor="White" />
                <StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
                <StaticSelectedStyle BackColor="#5D7B9D" />
            </asp:Menu>
        </div>

        <div>
            <section>
                <header><h1>Manage Payees</h1></header>
                <p>Select a Payee below to edit their information or select add new payee to create a new payee account.</p>
            </section>
        </div>


        <div>

            <header><h2>Add New Payee</h2></header>
            <section><p>Fill out the form to submit a new payee</p></section>

            <asp:Label ID="LBLPayeeName" runat="server" Text="Payee Name:" Width="125px"></asp:Label>
            <asp:TextBox ID="TXTPayeeName" runat="server" Width="300px"></asp:TextBox>
                <asp:RequiredFieldValidator
                    ID="VALIDPayeeName"
                    Runat="server"
                    ControlToValidate="TXTPayeeName"
                    Display="Dynamic"
                    ErrorMessage="*Payee Name is required"
                    ForeColor="red"
                    ValidationGroup="InsertControls">
                </asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Label ID="LBLPayeeAccountNumber" runat="server" Text="Account Number" Width="125px"></asp:Label>
            <asp:TextBox ID="TXTAccountNumber" runat="server" Width="300px" TextMode="Number"></asp:TextBox>
                <asp:RequiredFieldValidator
                    ID="VALIDAccountNumber"
                    Runat="server"
                    ControlToValidate="TXTAccountNumber"
                    Display="Dynamic"
                    ErrorMessage="*Payee account number is required!"
                    ForeColor="red"
                    ValidationGroup="InsertControls">
                </asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Label ID="LBLPayeeRoutingNumber" runat="server" Text="Routing Number:" Width="125px"></asp:Label>
            <asp:TextBox ID="TXTRoutingNumber" runat="server" Width="300px" TextMode="Number"></asp:TextBox>
                 <asp:RequiredFieldValidator
                    ID="VALIDRoutingNumber"
                    Runat="server"
                    ControlToValidate="TXTRoutingNumber"
                    Display="Dynamic"
                    ErrorMessage="*Payee routing number is a required field!"
                    ForeColor="red"
                    ValidationGroup="InsertControls">
                </asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Button ID="BTNAddNew" runat="server" Text="Add New Payee" OnClick="BTNAddNew_Click" ValidationGroup="InsertControls"/>
            <br />
            <br />
        </div>


        <div>
            <asp:GridView ID="GVPayeeData" runat="server" Width="600px" AutoGenerateDeleteButton="True" DataKeyNames="PayeeId,FK_UserID" AllowPaging="True" AutoGenerateColumns="False" DataSourceID="PayeeData" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateSelectButton="True">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:CommandField ShowEditButton="True" />
                    <asp:BoundField DataField="PayeeId" HeaderText="PayeeId" InsertVisible="False" ReadOnly="True" SortExpression="PayeeId" />
                    <asp:BoundField DataField="PayeeName" HeaderText="PayeeName" SortExpression="PayeeName" />
                    <asp:BoundField DataField="PayeeAccountNumber" HeaderText="PayeeAccountNumber" SortExpression="PayeeAccountNumber" />
                    <asp:BoundField DataField="PayeeRoutingNumber" HeaderText="PayeeRoutingNumber" SortExpression="PayeeRoutingNumber" />
                    <asp:BoundField DataField="FK_UserID" HeaderText="FK_UserID" Visible="False" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <asp:SqlDataSource ID="PayeeData" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT * FROM [PayeeData] WHERE ([FK_UserID] = @FK_UserID)" DeleteCommand="DELETE FROM [PayeeData] WHERE [PayeeId] = @PayeeId" UpdateCommand="UPDATE [PayeeData] SET [PayeeName] = @PayeeName, [PayeeAccountNumber] = @PayeeAccountNumber, [PayeeRoutingNumber] = @PayeeRoutingNumber, [FK_UserID] = @FK_UserID WHERE [PayeeId] = @PayeeId" InsertCommand="INSERT INTO [PayeeData] ([PayeeName], [PayeeAccountNumber], [PayeeRoutingNumber], [FK_UserID]) VALUES (@PayeeName, @PayeeAccountNumber, @PayeeRoutingNumber, @FK_UserID)">
                <DeleteParameters>
                    <asp:Parameter Name="PayeeId" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="PayeeName" Type="String" />
                    <asp:Parameter Name="PayeeAccountNumber" Type="String" />
                    <asp:Parameter Name="PayeeRoutingNumber" Type="String" />
                    <asp:Parameter Name="FK_UserID" Type="String" />
                </InsertParameters>
                <SelectParameters>
                    <asp:ControlParameter ControlID="LBLUserID" Name="FK_UserID" PropertyName="Text" Type="String" />
                </SelectParameters>
                <UpdateParameters>
                    <asp:Parameter Name="PayeeName" Type="String" />
                    <asp:Parameter Name="PayeeAccountNumber" Type="String" />
                    <asp:Parameter Name="PayeeRoutingNumber" Type="String" />
                    <asp:Parameter Name="FK_UserID" Type="String" />
                    <asp:Parameter Name="PayeeId" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <br />
            <asp:Label ID="LBLUpdatePayeeID" runat="server" Text="" Visible="false"></asp:Label>
            <asp:Label ID="LBLUserID" runat="server" Visible="False"></asp:Label>
            <br />
        </div>

    </form>
</body>
</html>
